server:
  port: 8084
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        enabed: true
  zipkin:
    enabled: true
    base-url: http://127.0.0.1:9411/ #zipkin地址
    sender:
      type: rabbit
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
    http:
      legacy:
        enabled: true