server:
  port: 8084
spring:
  profiles:
    active: dev
  application:
    name: nacos-provider
  cloud:  #nacos注册中心地址的配置法
    nacos:
      discovery:
        server-addr: localhost:8848  # nacos 注册中心的地址
      config:
        server-addr: localhost:8848  # nacos 注册中心的地址
        prefix: nacos-provider
        file-extension: yaml
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
